### ISSUE TITLE
Some Feature Suggestion

### ISSUE THREAD

**Issue by jbblily** [ksx0330/FVTT-Shinobigami-System#2]
I want to suggest some features needed for this system.

1. Can you show target figures right next to the talent's name, not hovering? 
I need to see the whole balance of target figures when I make a character.
2. Can you make abilities and finals automatically rolls certain talent? 

I appreciate your hard work.

안녕하세요, 본 시스템 잘 사용하고 있습니다. 
몇가지 기능을 제안하고 싶은데 고려해주셨으면 좋겠습니다. 

1. 특기의 목표치를 마우스 호버 시에 보이는 것이 아닌, 특기 이름 바로 옆에 항상 표시하도록 바꿔주실 수 있을까요?
시트 메이킹 시, 특기 간의 전체적인 거리를 고려하면서 짜는 것이 편리하기 때문에 개별 목표치보다는 전체의 목표치를 한눈에 보는 것이 좋을 것 같습니다. (그래야 거리가 너무 멀어서 목표치가 너무 높으면 조정할 수 있기 때문)
2. 인법이나 오의 사용 시 지정 특기를 자동으로 굴릴 수 있도록 자동화해주실 수 있을까요?

항상 좋은 시스템과 모듈 감사합니다.

**Comment by ksx0330** [comment]
Thank you for using it.
Among the requests, additional explanation is needed for No. 2.

The current system provides a button to roll the skill when using abilities and finals. 
Please explain in detail what other functions are needed.

사용해주셔서 감사합니다.
요청해주신 사항 중, 2번 사항에 대해 부가적인 설명이 필요합니다.

현 시스템에서는 인법 혹은 오의를 사용할 때 해당 특기 굴림을 할 수 있는 버튼을 제공하고 있습니다. 다른 어떤 기능이 필요한지 구체적인 설명 부탁드립니다.

**Comment by ksx0330** [comment]
Request 1 has been modified in version 1.0.2.
